source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-theme-primer"
gem "webrick", "~> 1.7"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-github-metadata"
end 