name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Install Dependencies
      run: |
        npm install
        npm install typescript@5.3.2
        npm install -D ts-node@10.9.1
        npm install -D @types/node@20.10.3
        npm install -D jest@29.7.0
        npm install -D ts-jest@29.1.1
        npm install -D @types/jest@29.5.10
        npm install -D supertest@6.3.3
        npm install -D @types/supertest@2.0.16

    - name: Type Check
      run: npx tsc --noEmit

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
      env:
        NODE_ENV: test
        JWT_SECRET: test-jwt-secret
        MONGODB_URI: mongodb://localhost:27017/test-db

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        flags: backend
        name: backend-coverage

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          ./dist
          ./node_modules/.cache
        key: ${{ runner.os }}-backend-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-backend-build-

    - name: Lint
      run: |
        npm install -g eslint
        npm install -D eslint-config-prettier
        npm install -D eslint-plugin-prettier
        npm install -D @typescript-eslint/eslint-plugin
        npm install -D @typescript-eslint/parser
        npx eslint . --ext .ts

    - name: Security Audit
      run: npm audit --production

    - name: Check Dependencies
      run: |
        echo "Checking for outdated dependencies..."
        npm outdated || true
        echo "Checking dependency tree..."
        npm ls || true
 