name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  FRONTEND_DIR: 'frontend'
  BACKEND_DIR: 'backend'
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  DIGITALOCEAN_CLUSTER_NAME: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
  KUBERNETES_CONFIG_DIR: 'k8s'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Frontend Dependencies
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm ci
      
      - name: Install Backend Dependencies
        working-directory: ${{ env.BACKEND_DIR }}
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm test
      
      - name: Run Backend Tests
        working-directory: ${{ env.BACKEND_DIR }}
        run: npm test

      - name: Build Frontend
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run build
      
      - name: Build Backend
        working-directory: ${{ env.BACKEND_DIR }}
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up doctl for DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_TOKEN }}
      
      - name: Save Kubernetes Config
        run: doctl kubernetes cluster kubeconfig save "${{ env.DIGITALOCEAN_CLUSTER_NAME }}"

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ${{ env.KUBERNETES_CONFIG_DIR }}/
          kubectl rollout restart deployment/frontend-deployment
          kubectl rollout restart deployment/backend-deployment
